### PR TITLE
SYNC-1681

### PR DESCRIPTION
**Pull request by shinnlok**

### CODE REVIEW

**Comment by mikemanyoung** [comment]
ci:retest

**Comment by mikemanyoung** [comment]
ci:retest

**Comment by shinnlok** [comment]
ci:retest

**Comment by mikemanyoung** [comment]
Merged and submitted to Brian if this is portal / plugin request. Thanks.
Pull request submitted at: https://github.com/brianchandotcom/liferay-portal/pull/44064
View total diff: https://github.com/mikemanyoung/liferay-portal/compare/8a3504c7f4...f68711e214

**Pull request closed without merging**
