### PR TITLE
SYNC-1441

### PR DESCRIPTION
**Pull request by shinnlok**

### CODE REVIEW

**Comment by shinnlok** [comment]
ci:retest

**Comment by mikemanyoung** [comment]
Merged and submitted to Brian if this is portal / plugin request. Thanks.
View total diff: https://github.com/mikemanyoung/liferay-portal/compare/f3ce6ec58d...46c51f68fe

**Comment by shinnlok** [comment]
Hey Mike,

This one never made it to Brian.

**Comment by mikemanyoung** [comment]
Ok. Will send it over later.

**Comment by mikemanyoung** [comment]
Merged and submitted to Brian if this is portal / plugin request. Thanks.
Pull request submitted at: https://github.com/brianchandotcom/liferay-portal/pull/30769
View total diff: https://github.com/mikemanyoung/liferay-portal/compare/46c51f68fe...46c51f68fe

**Comment by mikemanyoung** [comment]
Merged and submitted to Brian if this is portal / plugin request. Thanks.
Pull request submitted at: https://github.com/brianchandotcom/liferay-portal/pull/30770
View total diff: https://github.com/mikemanyoung/liferay-portal/compare/b6223360fa...00b12da595

**Pull request closed without merging**
