### PR TITLE
SYNC-1569

### PR DESCRIPTION
**Pull request by shinnlok**

### CODE REVIEW

**Comment by shinnlok** [comment]
ci:retest

**Comment by shinnlok** [comment]
ci:retest

**Comment by shinnlok** [comment]
ci:retest

**Comment by mikemanyoung** [comment]
Merged and submitted to Brian if this is portal / plugin request. Thanks.
Pull request submitted at: https://github.com/brianchandotcom/liferay-portal/pull/41323
View total diff: https://github.com/mikemanyoung/liferay-portal/compare/49e50ebcff...1faec6c738

**Pull request closed without merging**
